### PR TITLE
Strapi regulations and privacy policy

### PR DESCRIPTION
**Pull request by SebaKas21**

### CODE REVIEW

**Comment by SebaKas21** [comment]
@dawiddworak88 

From what I noticed, the components are created, but in the content manager, pages (Privacy Policy and Regulations) are blank

**Comment by SebaKas21** [comment]
Hi @dawiddworak88 

After deleting components from database. Content Builder page is blank

obraz

**Review by dawiddworak88 — APPROVED** [review]
Thank you

**Comment by dawiddworak88** [comment]
Hi @SebaKas21, could you please resolve the conflicts and test it once again?

**Comment by SebaKas21** [comment]
Hi @dawiddworak88

Can i merge this PR?

**Review by dawiddworak88 — APPROVED** [review]

**Pull request merged**
