### PR TITLE
Chnage order details

### PR DESCRIPTION
**Pull request by PiotrZaranek**

### CODE REVIEW

**Review by SebaKas21 — CHANGES_REQUESTED** [review]
HI @PiotrZaranek 

I thought about making it possible to set the expected date of a product in stock without having to change the status on FE

**Comment by dawiddworak88** [comment]
Hi @SebaKas21, I believe there might be a database migration missing to get rid of the two columns. Would you teach @PiotrZaranek what it is and how to generate them?

**Comment by SebaKas21** [comment]
@dawiddworak88  No problem 😁

**Comment by dawiddworak88** [comment]
Hi @SebaKas21, Hi @PiotrZaranek, please test whether Excel order import still works fine

**Comment by dawiddworak88** [comment]
@SebaKas21. @PiotrZaranek: please make sure the fields are adjusted / removed from the pop ups:

image

**Review by SebaKas21 — CHANGES_REQUESTED** [review]
Hi @PiotrZaranek 

If you can, center the input sections or stretch them. Also check the possibility of placing orders because I received status code -> 500

obraz

**Review by SebaKas21 — APPROVED** [review]
Hi @PiotrZaranek  Hi @dawiddworak88 For me it all works fine and I think it looks better now.

obraz

**Review by dawiddworak88 — APPROVED** [review]

**Pull request merged**
