### PR TITLE
Media management

### PR DESCRIPTION
**Pull request by SebaKas21**

### CODE REVIEW

**Comment by dawiddworak88** [comment]
Hi @SebaKas21 ,

could you please merge the develop branch to this branch, resolve conflicts, clean it, fix Codacy remarks and test carefully? We'll slowly merge it :)

Cheers,

**Comment by SebaKas21** [comment]
@dawiddworak88  Rest of improvements, i will make tomorrow

**Comment by SebaKas21** [comment]
@dawiddworak88 

In my opinion this PR is ready to merge, code fix and other improvements are done. 
Codacy errors are redundant (only space errors in webpack config)

**Review by dawiddworak88 — APPROVED** [review]
Let's give it a try 🚀

**Review by dawiddworak88 — CHANGES_REQUESTED** [review]
Hi @SebaKas21,

I checked it and I don't see any media already present in the media db? I believe they should be already there:

image

Cheers,

**Review by dawiddworak88 — APPROVED** [review]
OK, it's clear now 👍

**Pull request merged**
