### PR TITLE
Delivery addresses

### PR DESCRIPTION
**Pull request by SebaKas21**

### CODE REVIEW

**Review by PiotrZaranek — APPROVED** [review]

**Review by PiotrZaranek — COMMENTED** [review]
Hi @SebaKas21 i found bug when client addresse is edit in database it is created a new addresse with new values.

**Comment by SebaKas21** [comment]
Hi @PiotrZaranek, Hi @dawiddworak88 

You can check it one more time

**Review by dawiddworak88 — APPROVED** [review]
🥇

**Comment by dawiddworak88** [comment]
Hi @SebaKas21, would you please resolve the conflicts, test it and merge?

**Comment by SebaKas21** [comment]
Hi @dawiddworak88 

I tested and everything should be okay

**Pull request merged**
