### PR TITLE
Fixed endpoint for getting product by sku

### PR DESCRIPTION
**Pull request by SebaKas21**

### CODE REVIEW

**Review by dawiddworak88 — CHANGES_REQUESTED** [review]
Hi Sebastian, it should actually work with the keyword. Could you check whether it finds product with keyword suffix when it's lowercase, etc.?

**Comment by SebaKas21** [comment]
Hi @dawiddworak88 

I checked in the code and by writing the query manually. Success was true, but no data,

Without keyword searches in both cases

**Comment by SebaKas21** [comment]
@dawiddworak88 

What you think?

**Comment by dawiddworak88** [comment]
I fixed it by removing to lowercaseinvariant. Once we update the Elasticsearch version we'll add support for case insensitivity

**Pull request closed without merging**
