### PR TITLE
Client identity roles groups

### PR DESCRIPTION
**Pull request by SebaKas21**

### CODE REVIEW

**Comment by SebaKas21** [comment]
Hi @dawiddworak88,

At the moment, CRUD for roles is done, and what next? 
Revert changes from identity api?

**Review by dawiddworak88 — APPROVED** [review]
🥇

**Comment by dawiddworak88** [comment]
@SebaKas21 , could you please resolve conflicts and test it locally?

**Comment by SebaKas21** [comment]
@dawiddworak88  Resolved, can i merge?

**Review by dawiddworak88 — APPROVED** [review]

**Pull request merged**
