### PR TITLE
Improve docker_postgre_init file

### PR DESCRIPTION
**Pull request by PiotrZaranek**

### CODE REVIEW

**Review by SebaKas21 — APPROVED** [review]

**Comment by dawiddworak88** [comment]
Hi @SebaKas21, would you pull it and test on your localhost? Whether footer and links in menu nav pop up for all languages?

**Review by SebaKas21 — CHANGES_REQUESTED** [review]
Hi @PiotrZaranek,

When i merged develop to this branch. In container is a lot of errors:

obraz

**Comment by SebaKas21** [comment]
@PiotrZaranek That was problem on my docker. After deleting temp directory everything is okay, but new ones errors have appeared.

obraz

**Review by SebaKas21 — APPROVED** [review]
nothing more nothing less. Perfect @PiotrZaranek  🚀

**Review by dawiddworak88 — APPROVED** [review]

**Pull request merged**
